---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: resource-scripts

params:
  CF_API_ENDPOINT:
  SKIP_SSL_VALIDATION:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
  SECURITY_GROUP_NAME:
  SECURITY_GROUP_VALUE:
  PHASE:

run:
  path: resource-scripts/tasks/create-asg/task.sh
