---
resources:
- name: resource-scripts
  type: git
  source:
    uri: git@github.com:tom-collings/asg_job.git
    branch: master
    private_key: {{github-private-key}}


jobs:
- name: job-create-asg
  plan:
  - get: resource-scripts
  - task: create-asg
    file: resource-scripts/tasks/create-asg/task.yml
